import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int rolls) {

        int[] diceRolls = new int[rolls];
        Random random = new Random();

        for(int i = 0; i < rolls; i++) {
            diceRolls[i] = random.nextInt(6) + 1;
        }
        return diceRolls;
    }

    public boolean containsDuplicates(int[] input) {

        return false;
    }
}
