import java.util.Arrays;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public int[] roll(int rolls) {

        int[] diceRolls = new int[rolls];
        Random random = new Random();

        for(int i = 0; i < rolls; i++) {
            diceRolls[i] = random.nextInt(6) + 1;
        }
        return diceRolls;
    }

    public boolean containsDuplicates(int[] input) {

        for(int i = 0; i < input.length; i++) {
            for(int j = 0; j < input.length; j++){
                if(i != j) {
                    if(input[i] == input[j]){
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public int calculateAverage(int[] input) {

        double result = 0;

        for(int i = 0; i < input.length; i++) {
            result += input[i];
        }

        result = result / input.length;


        return (int) Math.round(result);
    }

    public int calculateAverageOfArrays(int[][] input) {

        int lowestAverage = calculateAverage(input[0]);

        for(int i = 1; i < input.length; i++) {

            int newAverage = calculateAverage(input[i]);

            if(newAverage < lowestAverage) {
                lowestAverage = newAverage;
            }
        }
        return lowestAverage;
    }
}
