/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testRoll() {
        Library classUnderTest = new Library();
        assertEquals("roll method should return 'true'", 6, classUnderTest.roll(6).length);
    }

    @Test
    public void testContainsDuplicates() {

    }
}
