import java.util.LinkedList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant {

    private String name;
    private int price;
    private int stars;
    LinkedList<Review> reviewList;

    public Restaurant(String name, int price) {
        this.name = name;
        this.price = price;
        this.stars = 0;
        this.reviewList = new LinkedList<>();
    }

    /**
     * Adds a review into the reviewList.
     */
    public void addReview(Review review) {
        reviewList.add(review);
        this.updateStars();
    }

    /**
     * Helper function to update the average Restaurant rating when review added.
     */
    private void updateStars() {
        int total = 0;
        for(Review review : reviewList) {
            total += review.getStars();
        }
        this.stars = total / reviewList.size();
    }

    public LinkedList getReviewList() {
        return reviewList;
    }

    public int getStars() {
        return stars;
    }
    
    @Override
    public String toString() {

        String priceSymbols = "";
        String starSymbols = "";
        String reviews = "";

        if(price <= 0) {
            priceSymbols = "$";
        }
        else {
            for(int i = 0; i < price; i++) {
                priceSymbols += "$";
            }
        }

        if(stars <= 0) {
            starSymbols = "No reviews.";
        }
        else {
            for(int i = 0; i < stars; i++) {
                starSymbols += "*";
            }
        }

        for(Review review : reviewList) {
            reviews += review.toString() + "\n";
        }

        return name + ": " + priceSymbols + ", " + starSymbols + "\n" + "Reviews: " + reviews;
    }
}
