import java.util.LinkedList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant implements Business {

    private String name;
    private int price;
    private int stars;
    LinkedList<Review> reviewList;

    public Restaurant(String name, int price) {
        this.name = name;
        this.price = price;
        this.stars = 0;
        this.reviewList = new LinkedList<>();
    }

    /**
     * Adds a review into the reviewList.
     */
    public void addReview(Review review) {
        review.setRestaurant(this);
        reviewList.add(review);
        this.updateStars();
    }

    /**
     * Helper function to update the average Restaurant rating when review added.
     */
    private void updateStars() {
        int total = 0;
        for(Review review : reviewList) {
            total += review.getStars();
        }
        this.stars = total / reviewList.size();
    }

    public LinkedList getReviewList() {
        return reviewList;
    }

    public int getStars() {
        return stars;
    }

    /**
     * Helper function that converts the int price to a string of dollar signs $$$
     * */
    private String convertPriceToSymbols() {
        String result = "";
        if(price <= 0) {
            return "$";
        }
        else {
            for(int i = 0; i < price; i++) {
                result += "$";
            }
        }
        return result;
    }

    /**
     * Helper function that converts the int star rating to a string of star signs ***
     * */
    private String convertStarsToSymbols() {
        String result = "";
        if(stars <= 0) {
            return "No reviews.";
        }
        else {
            for(int i = 0; i < stars; i++) {
                result += "*";
            }
        }
        return result;
    }

    @Override
    public String toString() {

        String priceSymbols = convertPriceToSymbols();
        String starSymbols = convertStarsToSymbols();
        String reviews = "";

        for(Review review : reviewList) {
            reviews += review.toString() + "\n";
        }

        return name + ": " + priceSymbols + ", " + starSymbols + "\n" + "Reviews: " + reviews;
    }
}
