/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.Buffer;

import static java.awt.image.BufferedImage.TYPE_INT_ARGB;
import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testFlipVertically() {

        Bitmap testWhiteTop = new Bitmap("resources/test_white_top.bmp", "resources/test_white_top_complete.bmp");
        testWhiteTop.flipVertically();

        assertEquals("check that image is black on top after flip vertically", Color.black.getRGB(), testWhiteTop.getImageData().getRGB(0, 0));
    }

    @Test
    public void testFlipHorizontally() {

        Bitmap testWhiteLeft = new Bitmap("resources/test_white_left.bmp", "resources/test_white_left_complete.bmp");
        testWhiteLeft.flipHorizontally();

        assertEquals("Check that image is black on the left after flip horizontally", Color.black.getRGB(), testWhiteLeft.getImageData().getRGB(0, 0));
    }

    @Test
    public void testAddRedBorder() {

        Bitmap testWhiteLeft = new Bitmap("resources/test_white_left.bmp", "resources/test_white_left_complete.bmp");
        testWhiteLeft.addRedBorder();

        assertEquals("Check that image has red border 5 pixels wide", Color.red.getRGB(), testWhiteLeft.getImageData().getRGB(0, 0));
        assertEquals("Check that image has red border 5 pixels wide", Color.red.getRGB(), testWhiteLeft.getImageData().getRGB(testWhiteLeft.getImageData().getWidth() / 2, testWhiteLeft.getImageData().getHeight() - 4));
    }

    @Test
    public void testBrighten() {
        Bitmap testAllBlack = new Bitmap("resources/test_all_black.bmp", "resources/test_all_black_complete.bmp");
        testAllBlack.brighten();

        assertTrue("Make sure all black picture is now lighter, color no longer black", Color.black.getRGB() != testAllBlack.getImageData().getRGB(0, 0));
    }

    @Test
    public void testDarken() {
        Bitmap testAllBlack = new Bitmap("resources/test_all_white.bmp", "resources/test_all_white_complete.bmp");
        testAllBlack.darken();

        assertTrue("Make sure all white picture is now darker, color no longer white", Color.white.getRGB() != testAllBlack.getImageData().getRGB(0, 0));
    }
}
