import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

//        for(String arg : args) {
//            System.out.println("\t" + arg);
//        }

        //Bitmap bitmap = new Bitmap(args[0], args[1], args[2]);

        // if args[2] == "flip"
        //    bitmap.flip();

        Bitmap bmp = new Bitmap(args[0], args[1], args[2]);



    }

}
